[package]
name = "rustLearn"
version = "0.1.0"
edition = "2021"

[dependencies]
gcp_auth = "0.12.3"
polars = { version="0.49.1", features=["lazy"] }
reqwest = "0.12.22"
serde = "1.0.219"
serde_json = "1.0.140"
thiserror = "2.0.12"
tokio = "1.46.1"

[[bin]]
name = "rustLearn"
path = "main.rs"
